/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package solent.ac.uk.ood.examples.swingcient.gui;

/**
 *
 * @author cgallen
 */
public class AppMainJFrame extends javax.swing.JFrame {
    
    /**
     * Model controller allows data to be injected into the component
     */
    private ModelController modelController =null;

    
        /**
     * Creates new form AppMainJFrame
     */
    public AppMainJFrame() {
        // giving dummy data to display
        this.modelController = new ModelController();
        initComponents();        
    }
    
    /**
     * Creates new form AppMainJFrame
     */
    public AppMainJFrame(ModelController modelController) {
        this.modelController = modelController;
        initComponents();        
    }

    public static void main(String[] args) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppMainJFrame().setVisible(true);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        // CUSTOM CODE injects modelController into panel
        controlsJPanel1 = new solent.ac.uk.ood.examples.swingcient.gui.ControlsJPanel(modelController);
        // CUSTOM CODE injects modelController into panel
        entityListScrollJpanel1 = new solent.ac.uk.ood.examples.swingcient.gui.EntityListScrollJpanel( modelController);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));
        getContentPane().add(controlsJPanel1);

        entityListScrollJpanel1.setAutoscrolls(true);
        getContentPane().add(entityListScrollJpanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private solent.ac.uk.ood.examples.swingcient.gui.ControlsJPanel controlsJPanel1;
    private solent.ac.uk.ood.examples.swingcient.gui.EntityListScrollJpanel entityListScrollJpanel1;
    // End of variables declaration//GEN-END:variables
}
