/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package solent.ac.uk.ood.examples.swingcient.gui;

/**
 *
 * @author cgallen
 */
public class ControlsJPanel extends javax.swing.JPanel {
    
    /**
     * Model controller allows data to be injected into the component
     */
    private ModelController modelController = null;

    /**
     * constructor which gives model controller to component
     *
     * @param modelController
     */
    public ControlsJPanel(ModelController modelController) {
        this.modelController = modelController;
        initComponents();

    }

    /**
     * Creates new form EntityListJPanel
     */
    public ControlsJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        entityFieldsJPanel1 = new solent.ac.uk.ood.examples.swingcient.gui.EntityFieldsJPanel();
        panel1 = new java.awt.Panel();
        findMatchingButton = new java.awt.Button();
        clearSearchButton = new java.awt.Button();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.X_AXIS));

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.X_AXIS));
        jPanel1.add(entityFieldsJPanel1);

        add(jPanel1);

        panel1.setMaximumSize(new java.awt.Dimension(102, 34));
        panel1.setLayout(new java.awt.GridLayout(1, 0));

        findMatchingButton.setActionCommand("findMatching");
        findMatchingButton.setLabel("Find Matching");
        findMatchingButton.setName("find"); // NOI18N
        findMatchingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findMatchingButtonActionPerformed(evt);
            }
        });
        panel1.add(findMatchingButton);

        clearSearchButton.setActionCommand("clearSearchButton");
        clearSearchButton.setLabel("Clear Search");
        clearSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearSearchButtonActionPerformed(evt);
            }
        });
        panel1.add(clearSearchButton);

        add(panel1);
    }// </editor-fold>//GEN-END:initComponents

    private void clearSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearSearchButtonActionPerformed
        // TODO add your handling code here:
        modelController.clearSearch();
    }//GEN-LAST:event_clearSearchButtonActionPerformed

    private void findMatchingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findMatchingButtonActionPerformed
        // TODO add your handling code here:
        modelController.findMatchingSearch();
    }//GEN-LAST:event_findMatchingButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button clearSearchButton;
    private solent.ac.uk.ood.examples.swingcient.gui.EntityFieldsJPanel entityFieldsJPanel1;
    private java.awt.Button findMatchingButton;
    private javax.swing.JPanel jPanel1;
    private java.awt.Panel panel1;
    // End of variables declaration//GEN-END:variables
}
