/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package solent.ac.uk.ood.examples.swingcient.newpackage.tmp;

import solent.ac.uk.ood.examples.swingcient.ModelControllerDummyImpl;
import solent.ac.uk.ood.examples.swingcient.EntityListTableModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author cgallen
 */
public class EntityListScrollJpanel extends javax.swing.JPanel {

    private EntityListTableModel entityListTableModel = null;

    /**
     * Model controller allows data to be injected into the component
     */
    private ModelControllerDummyImpl m_modelController = null;

    /**
     * constructor which gives model controller to component
     *
     * @param modelController
     */
    public EntityListScrollJpanel(ModelControllerDummyImpl modelController) {
        m_modelController = modelController;
        entityListTableModel = modelController.getEntityListTableModel();
        initComponents();

        jTable1.setModel(entityListTableModel);

        // list selected action
        jTable1.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent event) {
                // do some actions here, for example
                
                //Ignore extra events sent for selections
                if (event.getValueIsAdjusting()) {
                    return;
                }

                String entityIdstr = jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString();
                //m_modelController.findMatchingSearch(templateEntity);
            }
        });

    }

    /**
     * Creates new form ScrollPanel1
     */
    public EntityListScrollJpanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setDoubleBuffered(true);

        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
